version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - data-volume:/var/lib/postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  bundle:
  data-volume:
